### PR TITLE
Use InsertProbe instead of InsertKourierHeaders

### PR DESCRIPTION
**Pull request by nak3**
This patch changes to use InsertProbe instead of InsertKourierHeaders.

### CODE REVIEW

**Comment by nak3** [comment]
/retest

InsertProbe and InsertKourierHeaders are same functions for now.

https://github.com/knative-sandbox/net-kourier/blob/c31012c0d322c5b9ca2b998d5f71927c803eb92a/vendor/knative.dev/networking/pkg/ingress/ingress.go#L46-L66

https://github.com/knative-sandbox/net-kourier/blob/c31012c0d322c5b9ca2b998d5f71927c803eb92a/pkg/generator/ingress_translator.go#L293-L311

**Comment by nak3** [comment]
/hold

will work on this after https://github.com/knative-sandbox/net-kourier/pull/175

**Comment by nak3** [comment]
/hold cancel
/cc @davidor @jmprusi @markusthoemmes 

We need this as `InsertProbe` has this implementation https://github.com/knative/networking/pull/102 now.

**Review by davidor — APPROVED** [review]
/lgtm

**Pull request merged**
