### PR TITLE
Update envoy to 1.23

### PR DESCRIPTION
**Pull request by lionelvillard**
# Changes

- Update envoy to 1.23
- 
-

/kind enhancement

Fixes #

**Release Note**

```release-note
Update envoy to 1.23
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by nak3** [comment]
It seems CI is not passing with 1.23+? We will merge https://github.com/knative-sandbox/net-kourier/pull/921 first.

**Comment by lionelvillard** [comment]
1.21-1.23 releases introduced several breaking changes, dealing one release at a time sounds reasonable to me.

**Comment by nak3** [comment]
Closing as https://github.com/knative-sandbox/net-kourier/pull/976 included this.

**Pull request closed without merging**
