### PR TITLE
Name envoy config resources in a non-conflicting way

### PR DESCRIPTION
**Pull request by markusthoemmes**
Newer envoy versions seem to be more sensitive to how resources are named. Especially the VirtualHosts started colliding when multiple `Rules` are at play (which is often the case in Serving).

/hold

I want to send the test into the conformance suite and test this through serving thoroughly first too.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Verified to work in https://github.com/knative/serving/pull/10151

**Comment by markusthoemmes** [comment]
/unhold

Ready to go forward.

**Review by davidor — APPROVED** [review]

**Pull request merged**
