### PR TITLE
Enable chaos testing on net-kourier

### PR DESCRIPTION
**Pull request by mattmoor**
This matches similar PRs in:
 * net-istio: https://github.com/knative-sandbox/net-istio/pull/180
 * net-contour: https://github.com/knative-sandbox/net-contour/pull/158

/hold

### CODE REVIEW

**Comment by mattmoor** [comment]
Rebased this to pull in the latest chaos duck code, which was the verify codegen failure :(

**Comment by mattmoor** [comment]
@jmprusi if you are up for the next challenge, do the same for Serving, e.g. https://github.com/knative/serving/pull/8720

**Comment by mattmoor** [comment]
On second thought you are in the wrong namespace 🤔 

Do you have an issue tracking moving to knative-serving?  @markusthoemmes mentioned this might be in the cards recently.

**Comment by jmprusi** [comment]
@mattmoor I will open a PR to enable it after moving the namespace (just created the issue here https://github.com/knative-sandbox/net-kourier/issues/147)

**Pull request merged**
