### PR TITLE
Implement HostRewrite feature of Ingress

### LINKED ISSUE #159: Support Host Rewrite feature
The Host Rewrite feature was introduced as https://docs.google.com/document/d/1xK-g55kFdRRpYsiHyesmYWKURWi1sJlIWxMwkRmlyuM/edit

Kourier should implement it and passes the test https://github.com/knative/networking/blob/master/test/conformance/ingress/rewrite.go

Currently it is failing as https://github.com/knative-sandbox/net-kourier/pull/158 when enabled alpha flag.

### PR DESCRIPTION
**Pull request by markusthoemmes**
Fixes #159

1. This implements support for ExternalDomain type services (we might want to think about adding a conformance test for this specifically too).
2. This adds HostRewrite to the routes actually having it.

/assign @davidor @jmprusi

### CODE REVIEW

**Review by nak3 — APPROVED** [review]
LGTM!

**Comment by markusthoemmes** [comment]
Passed in https://github.com/knative/serving/pull/10075 

/unhold

**Comment by julz** [comment]
🤩🤩🤩 cool!

**Review by davidor — APPROVED** [review]
/lgtm

**Pull request merged**
