### PR TITLE
[master] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc davidor markusthoemmes tcnghia
/assign davidor markusthoemmes tcnghia

### CODE REVIEW

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by nak3** [comment]
I assume https://github.com/knative/pkg/pull/1821 will fix the issue.

**Review by tcnghia — APPROVED** [review]
/lgtm

**Pull request merged**
