### PR TITLE
Bump envoy image to 1.21 and add compatibility with 1.22

### LINKED ISSUE #907: Bump envoy image to 1.21
Currently gateway API uses envoy image is 1.20, but it will be EOL soon https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#major-release-schedule

We should bump the image version in:
- `config/300-gateway.yaml` (should update to 1.21.)
- `.github/workflows/kind-e2e.yaml`  (should test 1.21 and 1.22.)

### PR DESCRIPTION
**Pull request by tardieu**
# Changes

Bump envoy image to v1.21 and update kind-e2e.yaml to test against v1.21 and v.1.22.

Currently gateway API uses envoy image is 1.20, but it will be EOL soon https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#major-release-schedule

/kind enhancement

Fixes #907 

**Release Note**

```release-note
Bump Envoy version to v1.21 for Kourier gateway.
```

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm
/approve

Thank you! Could you sign in EasyCLA ?

**Comment by lionelvillard** [comment]
@nak3 several upgrade tests are not passing (pls). Is this expected?

**Comment by tardieu** [comment]
@nak3 I submitted the EasyCLA and I am waiting for IBM's corporate approver.

**Comment by nak3** [comment]
Thank you! Merged.

For the CI issue, yes I noticed it recently and need to be fixed.

**Pull request merged**
