### PR TITLE
Run kourier-gateway as user Envoy

### PR DESCRIPTION
**Pull request by bpinske**
Addresses operator issue
https://github.com/knative/operator/issues/710

# Changes

Run kourier-gateway as user Envoy

/kind enhancement

Fixes https://github.com/knative/operator/issues/710

```release-note
Run kourier-gateway as non-root
```

### CODE REVIEW

**Review by markusthoemmes — COMMENTED** [review]
/ok-to-test

**Comment by markusthoemmes** [comment]
This will sadly break on Openshift clusters, where a specific `runAs` stanza requires elevated rights. Have we considered talking to Envoy peeps to find out why the image has to be run as root otherwise?

**Comment by bpinske** [comment]
https://github.com/envoyproxy/envoy/issues/17610

**Pull request closed without merging**
