### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign davidor markusthoemmes
/cc davidor markusthoemmes

### CODE REVIEW

**Comment by jmprusi** [comment]
@mattmoor, we just merged https://github.com/knative-sandbox/net-kourier/pull/149 to pin some dependencies for the upcoming release. Should we merge this or wait until the release is complete?

**Comment by mattmoor** [comment]
/unhold

@jmprusi This respects the constraints in `update-deps`, and most of the diffs I see are test fixes to networking (cherry picked to release branch) which should help reduce flakiness, especially if you decide to start running ingress at a higher frequency to chase down flakes (e.g. https://github.com/knative-sandbox/net-istio/pull/223)

**Pull request merged**
