### PR TITLE
Move to go 1.17

### PR DESCRIPTION
**Pull request by skonto**
# Changes
- As per title. Other repos have already moved to 1.17.

### CODE REVIEW

**Review by nak3 — CHANGES_REQUESTED** [review]
github action - veirfy is failing https://github.com/knative-sandbox/net-kourier/runs/6451250983?check_suite_focus=true
Could you fix it?

**Comment by skonto** [comment]
Yes sure.

**Comment by skonto** [comment]
@nak3 ready.

**Pull request merged**
