### PR TITLE
Cleanup the reconciler file itself a bit

### PR DESCRIPTION
**Pull request by markusthoemmes**
A bit of a general cleanup. Mostly removes explicit name addition to loglines seeing as they are in the logger anyway and don't have to be repeated.

/assign @jmprusi @davidor

### CODE REVIEW

**Comment by markusthoemmes** [comment]
The errors here are genuine. I'll have to go check what's causing it.

**Comment by markusthoemmes** [comment]
Well I guess the DeepCopy is still needed. Will look into why that is the case separately.

**Comment by markusthoemmes** [comment]
/hold

The conflict should land first, I'll rebase this on that.

**Comment by markusthoemmes** [comment]
/unhold

Rebased.

**Review by tcnghia — APPROVED** [review]
/lgtm

**Pull request merged**
