### PR TITLE
Use new key names for internal encryption secret

### PR DESCRIPTION
**Pull request by KauzClay**
# Changes
:broom: Update or clean up current behavior
- New key names were added in https://github.com/knative-sandbox/control-protocol/pull/220
- Knative Serving was updated to use these new key names in https://github.com/knative/serving/pull/13388

/kind cleanup

Fixes #

**Release Note**

```release-note
N/A
```

**Docs**

```docs
N/A
```

### CODE REVIEW

**Comment by dprotaso** [comment]
Can you run `./hack/update-codegen.sh` but with go1.19 ?

**Comment by dprotaso** [comment]
Looks like all the e2e tests with TLS are failing consistently

**Comment by nak3** [comment]
I think the following script also needs to be updated from `ca-cert.pem` to `ca.crt`.

https://github.com/knative-sandbox/net-kourier/blob/f8f216baa52abcc689ae107661eb19ef578745dc/test/generate-upstream-cert.sh#L36

LGTM except for that.

**Comment by nak3** [comment]
Sorry, we have to add both `ca-cert.pem` and `ca.crt.` as upgrade test deploys previous version.
I verified it in https://github.com/knative-sandbox/net-kourier/pull/974 so please feel free to cherry-pick the commit.

**Comment by dprotaso** [comment]
@nak3 you should add yourself to `net-kourier-approvers` team - seems like you don't have permission here

/approve

**Pull request merged**
