### PR TITLE
Fix leader election issues due to defaults change

### PR DESCRIPTION
**Pull request by nak3**
This patch adds `test/config/leader-election.yaml` which was also added by https://github.com/knative/serving/pull/12506

### CODE REVIEW

**Comment by nak3** [comment]
/cc @rhuss @skonto

Could you please take a look? This is blocking the auto update https://github.com/knative-sandbox/net-kourier/pull/751.

**Comment by dprotaso** [comment]
Interesting - `visibility/split` errored out. I see this in net-contour and wondered if it was unique to us. Is this a kourier flake as well?

/retest

**Pull request merged**
