### PR TITLE
[Release-0.18] Pin deps to release-0.18

### PR DESCRIPTION
**Pull request by ZhiminXiang**

### CODE REVIEW

**Comment by tcnghia** [comment]
@ZhiminXiang looks like we need to get https://github.com/knative-sandbox/net-kourier/pull/196 first

**Comment by nak3** [comment]
@ZhiminXiang I hope that the issue was solved by https://github.com/knative-sandbox/net-kourier/commit/ae641abd14519c6dee5d30f32124092b02e7325a. Could you please rebase this?

**Review by tcnghia — APPROVED** [review]
/lgtm

**Pull request merged**
