### PR TITLE
Use default gRPC readiness probe

### PR DESCRIPTION
**Pull request by nak3**
As per title, this patch changes to use default gRPC readiness probe.

__Additional Note__
Current timeout is 100 milli seconds but `timeoutSeconds` is minimum 1 second so this change will make the timeout longer than current.

```
$ kubectl explain pod.spec.containers.readinessProbe.timeoutSeconds
KIND:     Pod
VERSION:  v1

FIELD:    timeoutSeconds <integer>

DESCRIPTION:
     Number of seconds after which the probe times out. Defaults to 1 second.
     Minimum value is 1. More info:
     https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
```

Fix https://github.com/knative-sandbox/net-kourier/issues/923

### CODE REVIEW

**Comment by nak3** [comment]
This will be a breaking change for the old k8s cluster (or OCP) so we will not merge until we are sure that the gRPC readiness probe is available. (after 1.10 or 1.11 release.)
But please feel free to ping here if somebody wants to get this PR merge. Downstream can make a patch if necessary.

**Comment by nak3** [comment]
/hold cancel
/cc @skonto @ReToCode 

This is now ready.

**Review by ReToCode — APPROVED** [review]
Nice, I like it.

/lgtm
/hold for other reviewers to chime in.

**Pull request merged**
