### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign davidor markusthoemmes
/cc davidor markusthoemmes

### CODE REVIEW

**Review by davidor — APPROVED** [review]
/lgtm

**Comment by tcnghia** [comment]
/hold
This may cause merge conflict for https://github.com/knative-sandbox/net-kourier/pull/184

**Comment by tcnghia** [comment]
@nak3 @davidor please feel free to /unhold whenever you are comfortable.

**Comment by nak3** [comment]
Thank you for holding this. This conflicted with #184. Let's merge next auto-update.

**Pull request closed without merging**
