### PR TITLE
Avoid setting the envoy snapshot twice per reconcile

### PR DESCRIPTION
**Pull request by markusthoemmes**
This **seems** unnecessary and maybe was needed because we used older envoy versions. Let's see what happens if we don't do this.

/assign @jmprusi @davidor

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Running here for additional stability testing: https://github.com/knative/serving/pull/10091

**Comment by davidor** [comment]
The PR that added this change is https://github.com/knative-sandbox/net-kourier/pull/45
There's a discussion there about why this was needed. I guess this was fixed in a recent version of Envoy. If we don't see any tests failing with the error in that PR I think it should be good to merge :+1:

**Comment by jmprusi** [comment]
Some of the serving tests failed, not sure if a flake... https://github.com/knative/serving/pull/10091

@markusthoemmes can you rebase and retry those tests?

**Comment by markusthoemmes** [comment]
@jmprusi done and all passed.

**Pull request merged**
