### PR TITLE
[Automated] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc davidor markusthoemmes
/assign davidor markusthoemmes

### CODE REVIEW

**Comment by nak3** [comment]
/hold

I think current `hack/update-deps.sh` is a little bit wrongly pinned. I will update it.

**Comment by mattmoor** [comment]
@nak3 what do you think is wrong?

**Comment by nak3** [comment]
@mattmoor sorry, never mind.

I found that `serving` is pinned to `master` but others (`pkg`, `networking`, `test-infra`) are `release-0.18`.

https://github.com/knative-sandbox/net-kourier/blob/bf7c4fb3ab51ac1d6cb833bf19808c9d9d049116/hack/update-deps.sh#L34-L39

But I realized that serving does not have the 0.18 branch yet. So, it is by design I think.

/hold cancel

**Comment by mattmoor** [comment]
@nak3 yeah, we're in the weird 1 week period where we're staging pkg before serving cuts.

**Review by davidor — APPROVED** [review]
/lgtm

**Pull request merged**
