### PR TITLE
Add missing perms for events and coordination via configmap.

### PR DESCRIPTION
**Pull request by jmprusi**

### CODE REVIEW

**Comment by davidor** [comment]
The tests are passing in other PRs without these permissions. Is this still needed?

**Comment by jmprusi** [comment]
@davidor yes! Tests are passing, but you will see several errors regarding the lack of permissions for events (not test failures.. ), so this pr fixes a couple things:

* When there's an error/warning, the controller will send an event, right now, that raises an error due to lack of perms.
* If the user has leader-election configure to use configmaps instead of leases, the controller will fail due to lack of perms. 

If you prefer I can split the PR!

**Pull request merged**
